macos_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-base:latest

  clone_script: |
    git clone -b "${CIRRUS_BRANCH}" https://github.com/adonis0147/pc-config "${HOME}/.config/pc-config"

  script: |
    cd "${HOME}/.config/pc-config"
    sed 's/^change_homebrew_mirror/# change_homebrew_mirror/' macOS/profile.zsh >macOS/profile.zsh.bak
    mv macOS/profile.zsh.bak macOS/profile.zsh
    bash install.sh

linux_task:
  compute_engine_instance:
    platform: linux
    image_project: cirrus-images
    image: family/docker-builder

  clone_script: |
    git clone -b "${CIRRUS_BRANCH}" https://github.com/adonis0147/pc-config "${HOME}/.config/pc-config"

  script: |
    cd "${HOME}/.config"

    cat >Dockerfile <<EOF
    FROM ubuntu:24.04
    RUN apt-get update
    RUN apt-get install --yes curl git lsb-release sudo python3
    ENV SHELL=bash
    CMD ["/bin/bash"]
    EOF

    docker build -t pc-config .
    sed -i 's/^install_snaps/# install_snaps/' pc-config/Linux/Ubuntu.zsh
    docker run --rm --mount=type=bind,source="$(pwd)/pc-config",target=/root/.config/pc-config pc-config \
      bash -c 'cd /root/.config/pc-config; bash install.sh'
